# A=str(input(""))
# B=str(input(""))
# C=str(input(""))
# triangle=12*float(A)*float(C)
# print(f"TRIANGULO: {triangle:.3f}")
A, B, C = input("").split()
triangle=0.5*float(A)*float(C)
radius=3.14159*(float(C)**2)
trapezium=0.5*(float(A)+float(B))*float(C)
square=(float(B)**2)
rectangle=float(A)*float(B)

print(f"TRIANGULO: {triangle:.3f}")
print(f"CIRCULO: {radius:.3f}")
print(f"TRAPEZIO: {trapezium:.3f}")
print(f"QUADRADO: {square:.3f}")
print(f"RETANGULO: {rectangle:.3f}")
